<template>
  <svg
    width="120"
    height="32"
    viewBox="0 0 120 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="2"
      y="7"
      width="18"
      height="18"
      rx="6"
      fill="var(--ui-primary)"
    />
    <rect
      x="8"
      y="1"
      width="18"
      height="18"
      rx="6"
      fill="color-mix(in srgb, var(--ui-primary) 72%, white)"
    />
    <rect
      x="14"
      y="7"
      width="18"
      height="18"
      rx="6"
      fill="#0f172a"
      opacity="0.14"
    />
    <text
      x="42"
      y="21"
      fill="currentColor"
      font-size="16"
      font-weight="700"
      letter-spacing="-0.03em"
    >Vue Board</text>
  </svg>
</template>
